name: ' '

on:
  push:
    paths:
      - 'packages/**'
      - 'apps/**'
      - 'tooling/**'
      - 'package.json'
      - 'bun.lock'
      - 'tsconfig*.json'
      - 'turbo.json'
      - 'biome.json'
      - '.oxlintrc.json'
      - '.github/workflows/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun i && cp .env.example .env && bun ci
